development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:e8746d1ab3d383f3258cfca0682ab99f@tarpon.redistogo.com:11795/
  channel_prefix: bingo_production
